<?php
/**
 * Created by PhpStorm.
 * User: David Leonardo V
 * Date: 15/05/2017
 * Time: 8:21 PM
 */
$this->layout('layout::default', ['title' => 'Home'])
?>
    <h1>Listado de Clientes</h1>

<style>
    table thead tr td {
        align-content: center;
        text-align: center;
        padding: 5px;
    }
</style>

    <table border="1" style="margin: 5px;">
        <thead>
            <tr>
                <td>Id</td>
                <td>Nit</td>
                <td>Nombre</td>
                <td>Dirección</td>
                <td>Cupo</td>
                <td>Saldo Cupo</td>
                <td>Porcentaje Visita</td>
                <td>Ciudad</td>
                <td> &nbsp; </td>
            </tr>
        </thead>
        <tbody>
        <?php
        /**
         * @var cliente Clientes
         */
        foreach ($clientes as $key => $cliente ) {?>
            <tr>
                <td><?= $cliente->getId() ?></td>
                <td><?= $cliente->getNit() ?></td>
                <td><?= $cliente->getNombre() ?></td>
                <td><?= $cliente->getDireccion() ?></td>
                <td><?= $cliente->getCupo() ?></td>
                <td><?= $cliente->getSaldoCupo() ?></td>
                <td><?= $cliente->getProcentajeVisita() ?></td>
                <td><?= $cliente->getCiudadesIdCiudades() ?></td>
                <td>
                    <a href="registrar-visita?idCliente=<?= $cliente->getId() ?>" >Reg Visita</a>
                </td>
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>

<?php $this->start('scripts') ?>
<?php $this->stop() ?>