<?php
/**
 * Created by PhpStorm.
 * User: David Leonardo V
 * Date: 15/05/2017
 * Time: 8:21 PM
 */
$this->layout('layout::default', ['title' => 'Home'])
?>
    <h1>Registro de cliente</h1>
    <p id="error" style="display: none;border: 2px solid red;" class="error" ></p>
    <p id="success" style="display: none;border: 2px solid blue;" class="success" ></p>
    <form id="reg-cliente-form" >
        <table style="margin-left: 40px;width: 99%;" >
            <tr>
                <td>Nit</td>
                <td>
                    <input type="text" name="nit" id="nit" />
                </td>
            </tr>
            <tr>
                <td>Nombre completo</td>
                <td>
                    <input type="text" name="nombreCompleto" id="nombreCompleto" />
                </td>
            </tr>
            <tr>
                <td>Dirección</td>
                <td>
                    <input type="text" name="direccion" id="direccion" />
                </td>
            </tr>
            <tr>
                <td>Teléfono</td>
                <td>
                    <input type="text" name="telefono" id="telefono" />
                </td>
            </tr>
            <tr>
                <td>Pais</td>
                <td>
                    <select name="pais" id="pais" >
                        <option>-seleccione-</option>
                        <?php
                        foreach ($paises as $pais) {
                            echo '<option value="'.$pais->getId().'" >'.$pais->getNombre().'</option>';
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Departamento</td>
                <td class=".departamentos" >
                    <select name="departamento" id="departamento" >
                        <option>-seleccione-</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Ciudad</td>
                <td>
                    <select name="ciudad" id="ciudad" >
                        <option>-seleccione-</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Cupo</td>
                <td>
                    <input type="number" name="cupo" id="cupo" />
                </td>
            </tr>
            <tr>
                <td colspan="2" >
                    <input type="button" name="save" id="save" value="Guardar" onclick="guardarCliente()" />
                </td>
            </tr>
        </table>
    </form>

<?php $this->start('scripts') ?>

    <script type="text/javascript" src="app/reg-cliente.js?v=<?= time() ?>" ></script>
    <script type="text/javascript" >
        if( $( "#reg-cliente-form" ).length ) {
            asignarEventos();
        }
    </script>

<?php $this->stop() ?>