<?php $this->layout('layout::default', ['title' => sprintf('%d %s', $status, $reason)]) ?>

<h1>Oops!</h1>
<h2>Esto es incomodo.</h2>
<p><?=$this->e($status)?>: <?=$this->e($reason)?></p>
<?php if ($status == 404) : ?>
    <p>
        You are looking for something that doesn't exist or may have moved. Check out one of the links on this page
        or head back to <a href="/">Home</a>.
    </p>
<?php endif; ?>
